<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAPTOP-B9RH7SGE" failures="2" tests="2" name="Default test(failed)" time="0.047" errors="0" timestamp="2022-04-22T02:52:37 IST">
  <testcase classname="pack123.TestNG123" name="testB" time="0.005">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at pack123.TestNG123.testB(TestNG123.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testB -->
  <testcase classname="pack123.TestNG123" name="testA" time="0.001">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at pack123.TestNG123.testA(TestNG123.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testA -->
  <testcase classname="pack123.TestNG123" name="testC" time="0.0">
    <ignored/>
  </testcase> <!-- testC -->
  <testcase classname="pack123.TestNG123" name="testD" time="0.0">
    <ignored/>
  </testcase> <!-- testD -->
</testsuite> <!-- Default test(failed) -->
